<a href="https://colab.research.google.com/github/ihzanursina/boilerplate-demographic-data-analyzer/blob/main/demographic_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/ihzanursina/boilerplate-demographic-data-analyzer/refs/heads/main/adult.data.csv"
df = pd.read_csv(url)

df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [5]:
race_count = df['race'].value_counts()
race_count

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

In [6]:
average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)
average_age_men

np.float64(39.4)

In [7]:
percentage_bachelors = round((df['education']== 'Bachelors').mean() * 100, 1)
percentage_bachelors

np.float64(16.4)

In [9]:
higher_education = df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])

In [12]:
lower_education = ~higher_education

In [13]:
higher_education_rich = round((df[higher_education]['salary']== '>50K').mean() * 100,1)
higher_education_rich

np.float64(46.5)

In [14]:
lower_education_rich = round((df[lower_education]['salary']== '>50K').mean() * 100,1)
lower_education_rich

np.float64(17.4)

In [15]:
min_work_hours = df['hours-per-week'].min()
min_work_hours

1

In [17]:
num_min_workers = df[df['hours-per-week'] == min_work_hours]

In [18]:
rich_percentage = round((num_min_workers['salary']== '>50K').mean() * 100,1)
rich_percentage

np.float64(10.0)

In [22]:
country_counts = df['native-country'].value_counts()

In [24]:
country_rich_counts = df[df['salary'] == '>50K']['native-country'].value_counts()

In [25]:
highest_earning_country = (country_rich_counts / country_counts * 100).idxmax()
highest_earning_country

'Iran'

In [26]:
highest_earning_country_percentage = round((country_rich_counts / country_counts * 100).max(),1)
highest_earning_country_percentage

41.9

In [27]:
top_IN_occupation = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]['occupation'].value_counts().idxmax()
top_IN_occupation

'Prof-specialty'

In [32]:
def calculate_demographic_data(print_data=True):
  url = "https://raw.githubusercontent.com/ihzanursina/boilerplate-demographic-data-analyzer/refs/heads/main/adult.data.csv"
  df = pd.read_csv(url)

  race_count = df['race'].value_counts()

  average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)

  percentage_bachelors = round((df['education']== 'Bachelors').mean() * 100, 1)

  higher_education = df['education'].isin(['Bachelors', 'Masters', 'Doctorate'])
  lower_education = ~higher_education

  higher_education_rich = round((df[higher_education]['salary']== '>50K').mean() * 100, 1)
  lower_education_rich = round((df[lower_education]['salary']== '>50K').mean() * 100, 1)

  min_work_hours = df['hours-per-week'].min()

  num_min_workers = df[df['hours-per-week'] == min_work_hours]

  rich_percentage = round((num_min_workers['salary']== '>50K').mean() * 100, 1)

  country_counts = df['native-country'].value_counts()
  country_rich_counts = df[df['salary'] == '>50K']['native-country'].value_counts()
  highest_earning_country = (country_rich_counts / country_counts * 100).idxmax()
  highest_earning_country_percentage = round((country_rich_counts / country_counts * 100).max(), 1)

  top_IN_occupation = df[(df['native-country'] == 'India') & (df['salary'] == '>50K')]['occupation'].value_counts().idxmax()

  if print_data:
        print("Number of each race:\n", race_count)
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print(f"Min work time: {min_work_hours} hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupations in India:", top_IN_occupation)

  return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage':
        highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }

In [34]:
calculate_demographic_data()

Number of each race:
 race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64
Average age of men: 39.4
Percentage with Bachelors degrees: 16.4%
Percentage with higher education that earn >50K: 46.5%
Percentage without higher education that earn >50K: 17.4%
Min work time: 1 hours/week
Percentage of rich among those who work fewest hours: 10.0%
Country with highest percentage of rich: Iran
Highest percentage of rich people in country: 41.9%
Top occupations in India: Prof-specialty

{'race_count': race
 White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
 Name: count, dtype: int64,
 'average_age_men': np.float64(39.4),
 'percentage_bachelors': np.float64(16.4),
 'higher_education_rich': np.float64(46.5),
 'lower_education_rich': np.float64(17.4),
 'min_work_hours': 1,
 'rich_percentage': np.float64(10.0),
 'highest_earning_country': 'Iran',
 'highest_earning_country_percentage': 41.9,
 'top_IN_occupation': 'Prof-specialty'}